services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: fastapi
    env_file:
      - .env
    volumes:
      - /srv:/srv
      - /root/scripts:/root/scripts:ro
      - /var/log/storagepod:/var/log/storagepod:ro
      - ./data:/app/db/data # this is for testing, remove in prod
    restart: always
    networks:
      - app_network
  nginx:
    image: nginx:latest
    ports:
      - "8443:443"
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - fastapi
    restart: always
    networks:
      - app_network
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: "0:0"
    network_mode: host
    restart: 'unless-stopped'
    volumes:
      - /srv/dev-disk-by-uuid-09698ee9-3b6f-4504-b43d-d7b527129ac9/Folder1:/media
    
networks:
  app_network:
    driver: bridge
