services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    env_file:
      - .env
    volumes:
      - /srv:/srv
      - /root/scripts:/root/scripts:ro
      - /var/log/storagepod:/var/log/storagepod:ro
    restart: always
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "8443:443"
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - fastapi
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
